steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build test image
    args:
      - "--dockerfile"
      - "docker/Dockerfile"
      - "--destination"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"
      - "--cache=true"
      - "--build-arg"
      - "PYTHON_PACKAGE_NAME=$_PYTHON_PACKAGE_NAME"

  - name: "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"
    id: Run mypi
    dir: /home/$_PYTHON_PACKAGE_NAME
    entrypoint: /bin/bash
    args:
      - "-c"
      - "make mypy"
    env:
      - 'PYTHON_PACKAGE_NAME=$_PYTHON_PACKAGE_NAME'

  - name: "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"
    id: Run test
    dir: /home/$_PYTHON_PACKAGE_NAME
    entrypoint: /bin/bash
    args:
      - "-c"
      - "make test"
    env:
      - 'PYTHON_PACKAGE_NAME=$_PYTHON_PACKAGE_NAME'

  - name: "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"
    id: Check code quality
    dir: /home/$_PYTHON_PACKAGE_NAME
    entrypoint: /bin/bash
    args:
      - "-c"
      - "make check_codequality"
    env:
      - 'PYTHON_PACKAGE_NAME=$_PYTHON_PACKAGE_NAME'

substitutions:
  _DOCKER_CACHE: "true"
  _PYTHON_PACKAGE_NAME: "pulumi_utils"
